# RUN THIS FILE LOCALLY WITH
# bundle exec jekyll serve --config _config_local.yml

title: Angela Zoss
email: angela.zoss@gmail.com
description: ""
theme: just-the-docs
#remote_theme: pmarsceill/just-the-docs

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.angelazoss.com" # the base hostname & protocol for your site, e.g. http://example.com

color_scheme: az_color

permalink: pretty

aux_links:
  Site Repository: https://github.com/amzoss/amzoss.github.io

collections:
  education:
    output: false
    display_name: "Education"
    display_order: 1
  job:
    output: true
    display_name: "Work Experience"
    display_order: 2
  service:
    output: false
    display_name: "Professional Service and Leadership Positions"
    display_order: 3
  tools:
    output: false
    display_name: "Skills and Experience"
    display_order: 4
  projects:
    output: true
    display_name: "Projects"
    display_order: 5
  project_archive:
    output: true
    display_name: "Projects"
    display_order: 6
  thesis:
    output: false
    display_name: "Theses/Dissertations"
    display_order: 7
  journal-article:
    output: false
    display_name: "Journal Articles"
    display_order: 8
  book-section:
    output: false
    display_name: "Book Chapters"
    display_order: 9
  conference-paper:
    output: false
    display_name: "Conference Papers"
    display_order: 10
  white-paper:
    output: false
    display_name: "White Papers"
    display_order: 11
  certification:
    output: false
    display_name: "Certifications"
    display_order: 12
  award:
    output: false
    display_name: "Awards/Honors"
    display_order: 13
  event:
    output: false
    display_name: "Event Participation"
    display_order: 14
  semester:
    output: false
    display_name: "Semester-Length Teaching Experiences"
    display_order: 15
  extended:
    output: false
    display_name: "Extended Workshop Instruction Experiences"
    display_order: 16
  conference-presentation:
    output: false
    display_name: "Presentations at Conferences, Professional Gatherings"
    display_order: 17
  guest:
    output: false
    display_name: "Guest Lectures"
    display_order: 18
  workshop:
    output: false
    display_name: "Short-form Instruction Experience"
    display_order: 19
  teaching:
    output: true
    display_name: "Teaching"
    display_order: 20
  themes:
    output: true
    display_name: "Areas of Focus"
    display_order: 21