# ==============================================================
# WAX CONFIGURATION
# ==============================================================
# Jekyll configuration files are written in YAML format.
# Colons, tabs/spacing, and quotes are meaningful in YAML.
# It is recommended you look at the following guide to avoid
# syntax errors in this file:
# ~> https://learnxinyminutes.com/docs/yaml/
#
#
# Questions ?
# ~> https://minicomp.github.io/wiki/#/
# ~> https://gitter.im/minicomp/wax/
#
# ---------------------------------------------------------------
# MAIN SETTINGS
# ---------------------------------------------------------------
# Feel free to change these! For more info, refer to:
# ~> https://jekyllrb.com/docs/configuration/options/

title:            'Angela Zoss'
description:      'Personal website of Angela Zoss'
url:              'https://amzoss.github.io'
baseurl:          '/'
copyright:        'Angela Zoss, 2020'
#logo:             '/assets/logo.png'

# ---------------------------------------------------------------
# BUILD SETTINGS
# ---------------------------------------------------------------
# Best not to mess with these unless you know what you're doing!

permalink: 'pretty'
sass:
  style: compressed
exclude:
  - Gemfile*
  - Rakefile
  - vendor
  - spec
  - README.md
webrick:
  headers:
    'Access-Control-Allow-Origin': '*'
kramdown:
 auto_ids:       true
 footnote_nr:    1
 entity_output:  as_char
 footnote_backlink: "&#x21a9;&#xfe0e;"
 toc_levels:     1..6
 smart_quotes:   lsquo,rsquo,ldquo,rdquo
 enable_coderay: false


# --------------------------------------------------------------
# COLLECTION SETTINGS
# --------------------------------------------------------------
# Wax leverages Jekyll collections for much of its
# functionality, therefor some of the keys below are from
# Jekyll while others are Wax-specific.
# For more info, refer to:
# ~> https://jekyllrb.com/docs/collections/

collections_dir: all_collections
collections:
  posts:
    output: true
    layout: 'page' # doesn't seem to work
  #exhibits:
  #  output: true
  projects:
    output: true
    layout: 'project'
    #permalink: /:pid
    metadata:
      source: 'projects.csv' # path to the metadata file within `_data`
    images:
      source: 'raw_images/projects' # path to the directory of images within `_data`
  awards:
    output: false
    metadata:
      source: 'awards.csv' # path to the metadata file within `_data`
  certifications:
    output: false
    metadata:
      source: 'certifications.csv' # path to the metadata file within `_data`
  chapters:
    output: false
    metadata:
      source: 'chapters.csv' # path to the metadata file within `_data`
  conferences:
    output: false
    metadata:
      source: 'conferences.csv' # path to the metadata file within `_data`
  education:
    output: false
    metadata:
      source: 'education.csv' # path to the metadata file within `_data`
  jobs:
    output: false
    metadata:
      source: 'jobs.csv' # path to the metadata file within `_data`
  journals:
    output: false
    metadata:
      source: 'journals.csv' # path to the metadata file within `_data`
  tools:
    output: false
    metadata:
      source: 'tools.csv' # path to the metadata file within `_data`
  presentations:
    output: false
    metadata:
      source: 'presentations.csv' # path to the metadata file within `_data`
  theses:
    output: false
    metadata:
      source: 'theses.csv' # path to the metadata file within `_data`
  reports:
    output: false
    metadata:
      source: 'reports.csv' # path to the metadata file within `_data`


# --------------------------------------------------------------
# SEARCH INDEX SETTINGS
# --------------------------------------------------------------
# You can create multiple search indexes below (though only one is
# recommended!) by specifying
# an `index` file to write it to and some `collections` for it to index
# and running `$ bundle exec rake wax:search` .

search:
  main:
    index: '/search/index.json' # file the index will get written to
    collections:
      theses:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - title
          - university
      journals:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - authors
          - title
          - journal
      chapters:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - authors
          - title
          - editor
          - book_title
      conferences:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - authors
          - title
          - editor
          - conference_name
          - conference_location
      reports:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - authors
          - title
          - description
      projects:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - title
          - collaborators
          - blurb
          - responsibilities
          - funding
      certifications:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - certification
      presentations:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - authors
          - title
          - location
          - host
          - type
      tools:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - grouping
          - tools_list
      awards:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - author
          - title
          - description
          - location
          - award
      education:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - institution
          - degree
          - thesis_title
          - thesis_type
          - committee
      jobs:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - job_title
          - location
          - department


# --------------------------------------------------------------
# SITE MENU SETTINGS
# --------------------------------------------------------------
# Each menu item needs a `label` (whats shown), and a `link`
# (where it goes). An item can optionally have a dropdown
# submenu via `sub`.

menu:
  - label: 'Resume'
    link: '/resume/'
  - label: 'Projects'
    link: '/projects/'
  - label: 'Posts'
    link: '/posts/'

# --------------------------------------------------------------
# SITE FOOTER SETTINGS
# --------------------------------------------------------------
#

footer:
  links:
    - label: 'GitHub'
      link: 'https://github.com/amzoss'
    - label: 'Credits'
      link: '/credits'
    - label: 'Contact'
      link: '/contact'
#  logos:
#    - img: '/img/logo.png'

# FIN
